// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYoKN5Jx0AV6bTETLmWrXfAkUemHh5x_0',
    appId: '1:481955215288:web:b45c1dc4a88fab6da2814d',
    messagingSenderId: '481955215288',
    projectId: 'demon-teach',
    authDomain: 'demon-teach.firebaseapp.com',
    storageBucket: 'demon-teach.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfPT5aObhGKAMCo0fkf-tOU3ayWQn2n4E',
    appId: '1:481955215288:android:c9b41549d971e277a2814d',
    messagingSenderId: '481955215288',
    projectId: 'demon-teach',
    storageBucket: 'demon-teach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDsS-sEaEU2u54sM5L9s6FBWSq0DfYVQ',
    appId: '1:481955215288:ios:452bbca81d7ea575a2814d',
    messagingSenderId: '481955215288',
    projectId: 'demon-teach',
    storageBucket: 'demon-teach.firebasestorage.app',
    iosBundleId: 'com.demonteach.demonTeach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVDsS-sEaEU2u54sM5L9s6FBWSq0DfYVQ',
    appId: '1:481955215288:ios:452bbca81d7ea575a2814d',
    messagingSenderId: '481955215288',
    projectId: 'demon-teach',
    storageBucket: 'demon-teach.firebasestorage.app',
    iosBundleId: 'com.demonteach.demonTeach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYoKN5Jx0AV6bTETLmWrXfAkUemHh5x_0',
    appId: '1:481955215288:web:a3d6525ca20b4b8ca2814d',
    messagingSenderId: '481955215288',
    projectId: 'demon-teach',
    authDomain: 'demon-teach.firebaseapp.com',
    storageBucket: 'demon-teach.firebasestorage.app',
  );
}
